# Site settings
title: "Murali.P"
email: p.murali730@gmail.com
description: "Its my personal blog where i'll post artciles realted to Dev-Ops technologies on every week"
baseurl: ""
url: "http://murali883.github.io"
title_description: "Skilled DevOps Engineer with 3+ years of hands-on experience supporting, automating, and optimizing mission critical deployments in AWS, leveraging configuration management, CI/CD, and DevOps processes."
title_image: "https://github.com/murali883/murali883.github.io/blob/master/assets/photo.png"
google_analytics: ""
disqus_account: Murali
github_repository: https://murali883.github.io
addthis_id: 
post_limit: 10

# Social usernames/URLs
twitter_username: murali8831
github_username:  murali883
linkedin_link: http://linkedin.com/in/murali-p-876ab1132
google_plus_link: 
stackoverflow_link:

# Footer
footer_left: "Template made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/murali8831\">Murali</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/murali883\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
